app:
  build: .
  # command: php artisan serve --host=0.0.0.0 --port=8080
  # ports:
  #   - 8080:8080
  links:
    - db
  volumes:
    - app:/code
db:
  image: mysql
  environment:
    MYSQL_DATABASE: application
    MYSQL_ROOT_PASSWORD: naberyakisikli
web:
  image: nginx
  links:
    - app
  ports:
    - 80:80
  volumes_from:
    - app
  volumes:
    - nginx.conf:/etc/nginx/conf.d/default.conf
    - logs/nginx:/var/log/nginx